version: "3.8"

services:
  kotlin:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kakeibo
      POSTGRES_USER: kakeibo_user
      POSTGRES_PASSWORD: kakeibo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: